# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AirsonicDesktop(object):
	def setupUi(self, AirsonicDesktop):
		AirsonicDesktop.setObjectName("AirsonicDesktop")
		AirsonicDesktop.resize(1500, 1200)
		self.centralwidget = QtWidgets.QWidget(AirsonicDesktop)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
		self.stackedWidget.setSizePolicy(sizePolicy)
		self.stackedWidget.setObjectName("stackedWidget")
		self.connectionSetup = QtWidgets.QWidget()
		self.connectionSetup.setObjectName("connectionSetup")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.connectionSetup)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setObjectName("formLayout")
		self.passwordInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.passwordInput.setObjectName("passwordInput")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
		self.passwordLabel = QtWidgets.QLabel(self.connectionSetup)
		self.passwordLabel.setObjectName("passwordLabel")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
		self.connectButton = QtWidgets.QPushButton(self.connectionSetup)
		self.connectButton.setObjectName("connectButton")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.connectButton)
		self.usernameInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.usernameInput.setObjectName("usernameInput")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
		self.domainInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.domainInput.setObjectName("domainInput")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.domainInput)
		self.usernameLabel = QtWidgets.QLabel(self.connectionSetup)
		self.usernameLabel.setObjectName("usernameLabel")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
		self.domainLabel = QtWidgets.QLabel(self.connectionSetup)
		self.domainLabel.setObjectName("domainLabel")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.domainLabel)
		spacerItem1 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
		self.horizontalLayout.addLayout(self.formLayout)
		spacerItem2 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem2)
		self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
		self.stackedWidget.addWidget(self.connectionSetup)
		self.mainPage = QtWidgets.QWidget()
		self.mainPage.setObjectName("mainPage")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.mainPage)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.splitter_2 = QtWidgets.QSplitter(self.mainPage)
		self.splitter_2.setOrientation(QtCore.Qt.Vertical)
		self.splitter_2.setObjectName("splitter_2")
		self.splitter = QtWidgets.QSplitter(self.splitter_2)
		self.splitter.setOrientation(QtCore.Qt.Horizontal)
		self.splitter.setObjectName("splitter")
		self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter)
		self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
		self.albumTreeListSearch = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
		self.albumTreeListSearch.setContentsMargins(0, 0, 0, 0)
		self.albumTreeListSearch.setObjectName("albumTreeListSearch")
		self.search = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
		self.search.setObjectName("search")
		self.albumTreeListSearch.addWidget(self.search)
		self.albumTreeList = QtWidgets.QTreeView(self.verticalLayoutWidget_3)
		self.albumTreeList.setObjectName("albumTreeList")
		self.albumTreeList.header().setDefaultSectionSize(17)
		self.albumTreeListSearch.addWidget(self.albumTreeList)
		self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.selectedAlbum = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.selectedAlbum.setContentsMargins(0, 0, 0, 0)
		self.selectedAlbum.setObjectName("selectedAlbum")
		self.selectedAlbumDetails = QtWidgets.QHBoxLayout()
		self.selectedAlbumDetails.setObjectName("selectedAlbumDetails")
		self.selectedAlbumArt = QtWidgets.QLabel(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.selectedAlbumArt.sizePolicy().hasHeightForWidth())
		self.selectedAlbumArt.setSizePolicy(sizePolicy)
		self.selectedAlbumArt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
		self.selectedAlbumArt.setObjectName("selectedAlbumArt")
		self.selectedAlbumDetails.addWidget(self.selectedAlbumArt)
		self.selectedAlbumTextDetails = QtWidgets.QVBoxLayout()
		self.selectedAlbumTextDetails.setObjectName("selectedAlbumTextDetails")
		self.selectedAlbumTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(20)
		font.setBold(True)
		font.setWeight(75)
		self.selectedAlbumTitle.setFont(font)
		self.selectedAlbumTitle.setTextInteractionFlags(
			QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
		self.selectedAlbumTitle.setObjectName("selectedAlbumTitle")
		self.selectedAlbumTextDetails.addWidget(self.selectedAlbumTitle)
		self.selectedAlbumArtist = QtWidgets.QLabel(self.verticalLayoutWidget)
		font = QtGui.QFont()
		font.setPointSize(14)
		self.selectedAlbumArtist.setFont(font)
		self.selectedAlbumArtist.setTextInteractionFlags(
			QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
		self.selectedAlbumArtist.setObjectName("selectedAlbumArtist")
		self.selectedAlbumTextDetails.addWidget(self.selectedAlbumArtist)
		self.selectedAlbumTextDetailsMinor = QtWidgets.QHBoxLayout()
		self.selectedAlbumTextDetailsMinor.setObjectName("selectedAlbumTextDetailsMinor")
		self.selectedAlbumTrackCountIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.selectedAlbumTrackCountIcon.sizePolicy().hasHeightForWidth())
		self.selectedAlbumTrackCountIcon.setSizePolicy(sizePolicy)
		self.selectedAlbumTrackCountIcon.setObjectName("selectedAlbumTrackCountIcon")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumTrackCountIcon)
		self.selectedAlbumTrackCount = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.selectedAlbumTrackCount.setObjectName("selectedAlbumTrackCount")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumTrackCount)
		self.selectedAlbumTotalLengthIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.selectedAlbumTotalLengthIcon.setObjectName("selectedAlbumTotalLengthIcon")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumTotalLengthIcon)
		self.selectedAlbumTotalLength = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.selectedAlbumTotalLength.setObjectName("selectedAlbumTotalLength")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumTotalLength)
		self.selectedAlbumReleaseYearIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.selectedAlbumReleaseYearIcon.setObjectName("selectedAlbumReleaseYearIcon")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumReleaseYearIcon)
		self.selectedAlbumReleaseYear = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.selectedAlbumReleaseYear.setObjectName("selectedAlbumReleaseYear")
		self.selectedAlbumTextDetailsMinor.addWidget(self.selectedAlbumReleaseYear)
		self.selectedAlbumTextDetails.addLayout(self.selectedAlbumTextDetailsMinor)
		self.selectedAlbumDetails.addLayout(self.selectedAlbumTextDetails)
		self.selectedAlbum.addLayout(self.selectedAlbumDetails)
		self.albumTrackList = QtWidgets.QTreeView(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.albumTrackList.sizePolicy().hasHeightForWidth())
		self.albumTrackList.setSizePolicy(sizePolicy)
		self.albumTrackList.setObjectName("albumTrackList")
		self.selectedAlbum.addWidget(self.albumTrackList)
		self.playQueueList = QtWidgets.QListWidget(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.playQueueList.sizePolicy().hasHeightForWidth())
		self.playQueueList.setSizePolicy(sizePolicy)
		self.playQueueList.setFlow(QtWidgets.QListView.TopToBottom)
		self.playQueueList.setViewMode(QtWidgets.QListView.ListMode)
		self.playQueueList.setObjectName("playQueueList")
		self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
		self.nowPlayingLayout = QtWidgets.QHBoxLayout()
		self.nowPlayingLayout.setObjectName("nowPlayingLayout")
		self.prevTrack = QtWidgets.QToolButton(self.mainPage)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.prevTrack.setIcon(icon)
		self.prevTrack.setObjectName("prevTrack")
		self.nowPlayingLayout.addWidget(self.prevTrack)
		self.playPause = QtWidgets.QToolButton(self.mainPage)
		self.playPause.setAutoFillBackground(False)
		self.playPause.setIcon(icon)
		self.playPause.setArrowType(QtCore.Qt.NoArrow)
		self.playPause.setObjectName("playPause")
		self.nowPlayingLayout.addWidget(self.playPause)
		self.nextTrack = QtWidgets.QToolButton(self.mainPage)
		self.nextTrack.setIcon(icon)
		self.nextTrack.setObjectName("nextTrack")
		self.nowPlayingLayout.addWidget(self.nextTrack)
		self.stop = QtWidgets.QToolButton(self.mainPage)
		self.stop.setIcon(icon)
		self.stop.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
		self.stop.setArrowType(QtCore.Qt.NoArrow)
		self.stop.setObjectName("stop")
		self.nowPlayingLayout.addWidget(self.stop)
		self.currentPlayingLabel = QtWidgets.QLabel(self.mainPage)
		self.currentPlayingLabel.setObjectName("currentPlayingLabel")
		self.nowPlayingLayout.addWidget(self.currentPlayingLabel)
		self.trackProgressBar = QtWidgets.QProgressBar(self.mainPage)
		self.trackProgressBar.setProperty("value", 0)
		self.trackProgressBar.setTextVisible(True)
		self.trackProgressBar.setFormat("")
		self.trackProgressBar.setObjectName("trackProgressBar")
		self.nowPlayingLayout.addWidget(self.trackProgressBar)
		self.gridLayout_3.addLayout(self.nowPlayingLayout, 1, 0, 1, 1)
		self.splitter_2.raise_()
		self.playQueueList.raise_()
		self.splitter_2.raise_()
		self.verticalLayoutWidget_3.raise_()
		self.stackedWidget.addWidget(self.mainPage)
		self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
		AirsonicDesktop.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(AirsonicDesktop)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 17))
		self.menubar.setObjectName("menubar")
		self.menuFile = QtWidgets.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		AirsonicDesktop.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(AirsonicDesktop)
		self.statusbar.setObjectName("statusbar")
		AirsonicDesktop.setStatusBar(self.statusbar)
		self.actionConnect = QtWidgets.QAction(AirsonicDesktop)
		self.actionConnect.setObjectName("actionConnect")
		self.actionExit = QtWidgets.QAction(AirsonicDesktop)
		self.actionExit.setObjectName("actionExit")
		self.menuFile.addAction(self.actionConnect)
		self.menuFile.addAction(self.actionExit)
		self.menubar.addAction(self.menuFile.menuAction())

		self.retranslateUi(AirsonicDesktop)
		self.stackedWidget.setCurrentIndex(1)
		QtCore.QMetaObject.connectSlotsByName(AirsonicDesktop)

	def retranslateUi(self, AirsonicDesktop):
		_translate = QtCore.QCoreApplication.translate
		AirsonicDesktop.setWindowTitle(_translate("AirsonicDesktop", "Airsonic Desktop"))
		self.passwordLabel.setText(_translate("AirsonicDesktop", "Password"))
		self.connectButton.setText(_translate("AirsonicDesktop", "Connect"))
		self.usernameLabel.setText(_translate("AirsonicDesktop", "Username"))
		self.domainLabel.setText(_translate("AirsonicDesktop", "Domain"))
		self.selectedAlbumArt.setText(_translate("AirsonicDesktop", "Album Art"))
		self.selectedAlbumTitle.setText(_translate("AirsonicDesktop", "Title"))
		self.selectedAlbumArtist.setText(_translate("AirsonicDesktop", "Artist"))
		self.selectedAlbumTrackCountIcon.setText(_translate("AirsonicDesktop", "CounIcon"))
		self.selectedAlbumTrackCount.setText(_translate("AirsonicDesktop", "Count"))
		self.selectedAlbumTotalLengthIcon.setText(_translate("AirsonicDesktop", "LengthIcon"))
		self.selectedAlbumTotalLength.setText(_translate("AirsonicDesktop", "Length"))
		self.selectedAlbumReleaseYearIcon.setText(_translate("AirsonicDesktop", "YearIcon"))
		self.selectedAlbumReleaseYear.setText(_translate("AirsonicDesktop", "Year"))
		self.prevTrack.setText(_translate("AirsonicDesktop", "..."))
		self.playPause.setText(_translate("AirsonicDesktop", "..."))
		self.nextTrack.setText(_translate("AirsonicDesktop", "..."))
		self.stop.setText(_translate("AirsonicDesktop", "..."))
		self.currentPlayingLabel.setText(_translate("AirsonicDesktop", "TextLabel"))
		self.menuFile.setTitle(_translate("AirsonicDesktop", "File"))
		self.actionConnect.setText(_translate("AirsonicDesktop", "Disconnect"))
		self.actionExit.setText(_translate("AirsonicDesktop", "Exit"))
