# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Thu Nov 21 01:37:56 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_AirsonicDesktop(object):
	def setupUi(self, AirsonicDesktop):
		AirsonicDesktop.setObjectName("AirsonicDesktop")
		AirsonicDesktop.resize(806, 677)
		self.centralwidget = QtWidgets.QWidget(AirsonicDesktop)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
		self.gridLayout.setObjectName("gridLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
		self.stackedWidget.setSizePolicy(sizePolicy)
		self.stackedWidget.setObjectName("stackedWidget")
		self.connectionSetup = QtWidgets.QWidget()
		self.connectionSetup.setObjectName("connectionSetup")
		self.gridLayout_2 = QtWidgets.QGridLayout(self.connectionSetup)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.formLayout = QtWidgets.QFormLayout()
		self.formLayout.setObjectName("formLayout")
		self.passwordInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.passwordInput.setObjectName("passwordInput")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordInput)
		self.passwordLabel = QtWidgets.QLabel(self.connectionSetup)
		self.passwordLabel.setObjectName("passwordLabel")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
		self.connectButton = QtWidgets.QPushButton(self.connectionSetup)
		self.connectButton.setObjectName("connectButton")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.connectButton)
		self.usernameInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.usernameInput.setObjectName("usernameInput")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
		self.domainInput = QtWidgets.QLineEdit(self.connectionSetup)
		self.domainInput.setObjectName("domainInput")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.domainInput)
		self.usernameLabel = QtWidgets.QLabel(self.connectionSetup)
		self.usernameLabel.setObjectName("usernameLabel")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
		self.domainLabel = QtWidgets.QLabel(self.connectionSetup)
		self.domainLabel.setObjectName("domainLabel")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.domainLabel)
		spacerItem1 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
		self.horizontalLayout.addLayout(self.formLayout)
		spacerItem2 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem2)
		self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
		self.stackedWidget.addWidget(self.connectionSetup)
		self.mainPage = QtWidgets.QWidget()
		self.mainPage.setObjectName("mainPage")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.mainPage)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.splitter_2 = QtWidgets.QSplitter(self.mainPage)
		self.splitter_2.setOrientation(QtCore.Qt.Vertical)
		self.splitter_2.setObjectName("splitter_2")
		self.splitter = QtWidgets.QSplitter(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
		self.splitter.setSizePolicy(sizePolicy)
		self.splitter.setOrientation(QtCore.Qt.Horizontal)
		self.splitter.setObjectName("splitter")
		self.albumTreeList = QtWidgets.QTreeView(self.splitter)
		self.albumTreeList.setObjectName("albumTreeList")
		self.albumTreeList.header().setDefaultSectionSize(17)
		self.albumTrackList = QtWidgets.QListView(self.splitter)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.albumTrackList.sizePolicy().hasHeightForWidth())
		self.albumTrackList.setSizePolicy(sizePolicy)
		self.albumTrackList.setObjectName("albumTrackList")
		self.playQueueList = QtWidgets.QListWidget(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.playQueueList.sizePolicy().hasHeightForWidth())
		self.playQueueList.setSizePolicy(sizePolicy)
		self.playQueueList.setFlow(QtWidgets.QListView.TopToBottom)
		self.playQueueList.setViewMode(QtWidgets.QListView.ListMode)
		self.playQueueList.setObjectName("playQueueList")
		self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
		self.nowPlayingLayout = QtWidgets.QHBoxLayout()
		self.nowPlayingLayout.setObjectName("nowPlayingLayout")
		self.prevTrack = QtWidgets.QToolButton(self.mainPage)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.prevTrack.setIcon(icon)
		self.prevTrack.setObjectName("prevTrack")
		self.nowPlayingLayout.addWidget(self.prevTrack)
		self.playPause = QtWidgets.QToolButton(self.mainPage)
		self.playPause.setIcon(icon)
		self.playPause.setObjectName("playPause")
		self.nowPlayingLayout.addWidget(self.playPause)
		self.nextTrack = QtWidgets.QToolButton(self.mainPage)
		self.nextTrack.setIcon(icon)
		self.nextTrack.setObjectName("nextTrack")
		self.nowPlayingLayout.addWidget(self.nextTrack)
		self.stop = QtWidgets.QToolButton(self.mainPage)
		self.stop.setIcon(icon)
		self.stop.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
		self.stop.setArrowType(QtCore.Qt.NoArrow)
		self.stop.setObjectName("stop")
		self.nowPlayingLayout.addWidget(self.stop)
		self.currentPlayingLabel = QtWidgets.QLabel(self.mainPage)
		self.currentPlayingLabel.setObjectName("currentPlayingLabel")
		self.nowPlayingLayout.addWidget(self.currentPlayingLabel)
		self.trackProgressBar = QtWidgets.QProgressBar(self.mainPage)
		self.trackProgressBar.setProperty("value", 0)
		self.trackProgressBar.setTextVisible(True)
		self.trackProgressBar.setFormat("")
		self.trackProgressBar.setObjectName("trackProgressBar")
		self.nowPlayingLayout.addWidget(self.trackProgressBar)
		self.gridLayout_3.addLayout(self.nowPlayingLayout, 1, 0, 1, 1)
		self.stackedWidget.addWidget(self.mainPage)
		self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
		AirsonicDesktop.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(AirsonicDesktop)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 17))
		self.menubar.setObjectName("menubar")
		self.menuFile = QtWidgets.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		AirsonicDesktop.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(AirsonicDesktop)
		self.statusbar.setObjectName("statusbar")
		AirsonicDesktop.setStatusBar(self.statusbar)
		self.actionConnect = QtWidgets.QAction(AirsonicDesktop)
		self.actionConnect.setObjectName("actionConnect")
		self.actionExit = QtWidgets.QAction(AirsonicDesktop)
		self.actionExit.setObjectName("actionExit")
		self.menuFile.addAction(self.actionConnect)
		self.menuFile.addAction(self.actionExit)
		self.menubar.addAction(self.menuFile.menuAction())

		self.retranslateUi(AirsonicDesktop)
		self.stackedWidget.setCurrentIndex(1)
		QtCore.QMetaObject.connectSlotsByName(AirsonicDesktop)

	def retranslateUi(self, AirsonicDesktop):
		AirsonicDesktop.setWindowTitle(
			QtWidgets.QApplication.translate("AirsonicDesktop", "Airsonic Desktop", None, -1))
		self.passwordLabel.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Password", None, -1))
		self.connectButton.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Connect", None, -1))
		self.usernameLabel.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Username", None, -1))
		self.domainLabel.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Domain", None, -1))
		self.prevTrack.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "...", None, -1))
		self.playPause.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "...", None, -1))
		self.nextTrack.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "...", None, -1))
		self.stop.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "...", None, -1))
		self.currentPlayingLabel.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "TextLabel", None, -1))
		self.menuFile.setTitle(QtWidgets.QApplication.translate("AirsonicDesktop", "File", None, -1))
		self.actionConnect.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Disconnect", None, -1))
		self.actionExit.setText(QtWidgets.QApplication.translate("AirsonicDesktop", "Exit", None, -1))
