name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install poetry
        run: |
          (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python
      - name: Install dependencies
        run: .$env:USERPROFILE\.poetry\bin\poetry.bat install
      - name: Build app
        run: .(get-item $env:LOCALAPPDATA\pypoetry\Cache\virtualenvs\vapoursonic-*-py3.6\Scripts\python.exe).FullName -m fbs freeze
      - name: Download+Install NSIS, make installer
        run: .(get-item '.github\nsis.ps1').FullName
      - name: Archive Installer artifact
        uses: actions/upload-artifact@v1
        with:
          name: installer
          path: target\vapoursonicSetup.exe